/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { AxiosInstance, AxiosPromise, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
import type { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  createRequestFunction,
  serializeDataIfNeeded,
  setBearerAuthToObject,
  setSearchParams,
  toPathString,
} from '../common';
// @ts-ignore
import {
  BASE_PATH,
  BaseAPI,
  operationServerMap,
  type RequestArgs,
} from '../base';
// @ts-ignore
import type { CommonResCounselCardBaseInformationRes } from '../models';
// @ts-ignore
import type { CommonResCounselCardHealthInformationRes } from '../models';
// @ts-ignore
import type { CommonResCounselCardIdRes } from '../models';
// @ts-ignore
import type { CommonResCounselCardIndependentLifeInformationRes } from '../models';
// @ts-ignore
import type { CommonResCounselCardLivingInformationRes } from '../models';
// @ts-ignore
import type { CommonResCounselCardRes } from '../models';
// @ts-ignore
import type { CommonResListTimeRecordedResObject } from '../models';
// @ts-ignore
// @ts-ignore
// @ts-ignore
import type { UpdateBaseInformationReq } from '../models';
// @ts-ignore
import type { UpdateCounselCardStatusReq } from '../models';
// @ts-ignore
import type { UpdateHealthInformationReq } from '../models';
// @ts-ignore
import type { UpdateIndependentLifeInformationReq } from '../models';
// @ts-ignore
import type { UpdateLivingInformationReq } from '../models';
/**
 * CounselCardControllerApi - axios parameter creator
 * @export
 */
export const CounselCardControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 상담 카드 삭제
         * @param {string} counselSessionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteCounselCard: async (counselSessionId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'counselSessionId' is not null or undefined
            assertParamExists('deleteCounselCard', 'counselSessionId', counselSessionId)
            const localVarPath = `/v1/counsel/card/{counselSessionId}`
                .replace(`{${"counselSessionId"}}`, encodeURIComponent(String(counselSessionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 상담 카드 조회
         * @param {string} counselSessionId 
         * @param {*} [options] Override http request option.
         * @deprecated
         * @throws {RequiredError}
         */
        selectCounselCard: async (counselSessionId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'counselSessionId' is not null or undefined
            assertParamExists('selectCounselCard', 'counselSessionId', counselSessionId)
            const localVarPath = `/v1/counsel/card/{counselSessionId}`
                .replace(`{${"counselSessionId"}}`, encodeURIComponent(String(counselSessionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 상담 카드 기본 정보 조회
         * @param {string} counselSessionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        selectCounselCardBaseInformation: async (counselSessionId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'counselSessionId' is not null or undefined
            assertParamExists('selectCounselCardBaseInformation', 'counselSessionId', counselSessionId)
            const localVarPath = `/v1/counsel/card/{counselSessionId}/base-information`
                .replace(`{${"counselSessionId"}}`, encodeURIComponent(String(counselSessionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 상담 카드 건강 정보 조회
         * @param {string} counselSessionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        selectCounselCardHealthInformation: async (counselSessionId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'counselSessionId' is not null or undefined
            assertParamExists('selectCounselCardHealthInformation', 'counselSessionId', counselSessionId)
            const localVarPath = `/v1/counsel/card/{counselSessionId}/health-information`
                .replace(`{${"counselSessionId"}}`, encodeURIComponent(String(counselSessionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 상담 카드 자립생활 역량 조회
         * @param {string} counselSessionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        selectCounselCardIndependentLifeInformation: async (counselSessionId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'counselSessionId' is not null or undefined
            assertParamExists('selectCounselCardIndependentLifeInformation', 'counselSessionId', counselSessionId)
            const localVarPath = `/v1/counsel/card/{counselSessionId}/independent-information`
                .replace(`{${"counselSessionId"}}`, encodeURIComponent(String(counselSessionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 상담 카드 생활 정보 조회
         * @param {string} counselSessionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        selectCounselCardLivingInformation: async (counselSessionId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'counselSessionId' is not null or undefined
            assertParamExists('selectCounselCardLivingInformation', 'counselSessionId', counselSessionId)
            const localVarPath = `/v1/counsel/card/{counselSessionId}/living-information`
                .replace(`{${"counselSessionId"}}`, encodeURIComponent(String(counselSessionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 이전 상담 카드 item 목록 조회
         * @param {string} counselSessionId 
         * @param {SelectPreviousItemListByInformationNameAndItemNameTypeEnum} type 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        selectPreviousItemListByInformationNameAndItemName: async (counselSessionId: string, type: SelectPreviousItemListByInformationNameAndItemNameTypeEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'counselSessionId' is not null or undefined
            assertParamExists('selectPreviousItemListByInformationNameAndItemName', 'counselSessionId', counselSessionId)
            // verify required parameter 'type' is not null or undefined
            assertParamExists('selectPreviousItemListByInformationNameAndItemName', 'type', type)
            const localVarPath = `/v1/counsel/card/{counselSessionId}/previous/item/list`
                .replace(`{${"counselSessionId"}}`, encodeURIComponent(String(counselSessionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (type !== undefined) {
                localVarQueryParameter['type'] = type;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 상담 카드 기본 정보 수정
         * @param {string} counselSessionId 
         * @param {UpdateBaseInformationReq} updateBaseInformationReq 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateCounselCardBaseInformation: async (counselSessionId: string, updateBaseInformationReq: UpdateBaseInformationReq, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'counselSessionId' is not null or undefined
            assertParamExists('updateCounselCardBaseInformation', 'counselSessionId', counselSessionId)
            // verify required parameter 'updateBaseInformationReq' is not null or undefined
            assertParamExists('updateCounselCardBaseInformation', 'updateBaseInformationReq', updateBaseInformationReq)
            const localVarPath = `/v1/counsel/card/{counselSessionId}/base-information`
                .replace(`{${"counselSessionId"}}`, encodeURIComponent(String(counselSessionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateBaseInformationReq, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 상담 카드 건강 정보 수정
         * @param {string} counselSessionId 
         * @param {UpdateHealthInformationReq} updateHealthInformationReq 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateCounselCardHealthInformation: async (counselSessionId: string, updateHealthInformationReq: UpdateHealthInformationReq, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'counselSessionId' is not null or undefined
            assertParamExists('updateCounselCardHealthInformation', 'counselSessionId', counselSessionId)
            // verify required parameter 'updateHealthInformationReq' is not null or undefined
            assertParamExists('updateCounselCardHealthInformation', 'updateHealthInformationReq', updateHealthInformationReq)
            const localVarPath = `/v1/counsel/card/{counselSessionId}/health-information`
                .replace(`{${"counselSessionId"}}`, encodeURIComponent(String(counselSessionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateHealthInformationReq, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 상담 카드 자립생활 역량 수정
         * @param {string} counselSessionId 
         * @param {UpdateIndependentLifeInformationReq} updateIndependentLifeInformationReq 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateCounselCardIndependentLifeInformation: async (counselSessionId: string, updateIndependentLifeInformationReq: UpdateIndependentLifeInformationReq, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'counselSessionId' is not null or undefined
            assertParamExists('updateCounselCardIndependentLifeInformation', 'counselSessionId', counselSessionId)
            // verify required parameter 'updateIndependentLifeInformationReq' is not null or undefined
            assertParamExists('updateCounselCardIndependentLifeInformation', 'updateIndependentLifeInformationReq', updateIndependentLifeInformationReq)
            const localVarPath = `/v1/counsel/card/{counselSessionId}/independent-life-information`
                .replace(`{${"counselSessionId"}}`, encodeURIComponent(String(counselSessionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateIndependentLifeInformationReq, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 상담 카드 생활 정보 수정
         * @param {string} counselSessionId 
         * @param {UpdateLivingInformationReq} updateLivingInformationReq 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateCounselCardLivingInformation: async (counselSessionId: string, updateLivingInformationReq: UpdateLivingInformationReq, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'counselSessionId' is not null or undefined
            assertParamExists('updateCounselCardLivingInformation', 'counselSessionId', counselSessionId)
            // verify required parameter 'updateLivingInformationReq' is not null or undefined
            assertParamExists('updateCounselCardLivingInformation', 'updateLivingInformationReq', updateLivingInformationReq)
            const localVarPath = `/v1/counsel/card/{counselSessionId}/living-information`
                .replace(`{${"counselSessionId"}}`, encodeURIComponent(String(counselSessionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateLivingInformationReq, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 상담 카드 상태 수정
         * @param {string} counselSessionId 
         * @param {UpdateCounselCardStatusReq} updateCounselCardStatusReq 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateCounselCardStatus: async (counselSessionId: string, updateCounselCardStatusReq: UpdateCounselCardStatusReq, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'counselSessionId' is not null or undefined
            assertParamExists('updateCounselCardStatus', 'counselSessionId', counselSessionId)
            // verify required parameter 'updateCounselCardStatusReq' is not null or undefined
            assertParamExists('updateCounselCardStatus', 'updateCounselCardStatusReq', updateCounselCardStatusReq)
            const localVarPath = `/v1/counsel/card/{counselSessionId}/status`
                .replace(`{${"counselSessionId"}}`, encodeURIComponent(String(counselSessionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateCounselCardStatusReq, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CounselCardControllerApi - functional programming interface
 * @export
 */
export const CounselCardControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CounselCardControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary 상담 카드 삭제
         * @param {string} counselSessionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteCounselCard(counselSessionId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommonResCounselCardIdRes>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteCounselCard(counselSessionId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CounselCardControllerApi.deleteCounselCard']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 상담 카드 조회
         * @param {string} counselSessionId 
         * @param {*} [options] Override http request option.
         * @deprecated
         * @throws {RequiredError}
         */
        async selectCounselCard(counselSessionId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommonResCounselCardRes>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.selectCounselCard(counselSessionId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CounselCardControllerApi.selectCounselCard']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 상담 카드 기본 정보 조회
         * @param {string} counselSessionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async selectCounselCardBaseInformation(counselSessionId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommonResCounselCardBaseInformationRes>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.selectCounselCardBaseInformation(counselSessionId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CounselCardControllerApi.selectCounselCardBaseInformation']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 상담 카드 건강 정보 조회
         * @param {string} counselSessionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async selectCounselCardHealthInformation(counselSessionId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommonResCounselCardHealthInformationRes>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.selectCounselCardHealthInformation(counselSessionId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CounselCardControllerApi.selectCounselCardHealthInformation']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 상담 카드 자립생활 역량 조회
         * @param {string} counselSessionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async selectCounselCardIndependentLifeInformation(counselSessionId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommonResCounselCardIndependentLifeInformationRes>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.selectCounselCardIndependentLifeInformation(counselSessionId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CounselCardControllerApi.selectCounselCardIndependentLifeInformation']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 상담 카드 생활 정보 조회
         * @param {string} counselSessionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async selectCounselCardLivingInformation(counselSessionId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommonResCounselCardLivingInformationRes>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.selectCounselCardLivingInformation(counselSessionId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CounselCardControllerApi.selectCounselCardLivingInformation']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 이전 상담 카드 item 목록 조회
         * @param {string} counselSessionId 
         * @param {SelectPreviousItemListByInformationNameAndItemNameTypeEnum} type 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async selectPreviousItemListByInformationNameAndItemName(counselSessionId: string, type: SelectPreviousItemListByInformationNameAndItemNameTypeEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommonResListTimeRecordedResObject>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.selectPreviousItemListByInformationNameAndItemName(counselSessionId, type, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CounselCardControllerApi.selectPreviousItemListByInformationNameAndItemName']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 상담 카드 기본 정보 수정
         * @param {string} counselSessionId 
         * @param {UpdateBaseInformationReq} updateBaseInformationReq 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateCounselCardBaseInformation(counselSessionId: string, updateBaseInformationReq: UpdateBaseInformationReq, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommonResCounselCardIdRes>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateCounselCardBaseInformation(counselSessionId, updateBaseInformationReq, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CounselCardControllerApi.updateCounselCardBaseInformation']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 상담 카드 건강 정보 수정
         * @param {string} counselSessionId 
         * @param {UpdateHealthInformationReq} updateHealthInformationReq 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateCounselCardHealthInformation(counselSessionId: string, updateHealthInformationReq: UpdateHealthInformationReq, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommonResCounselCardIdRes>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateCounselCardHealthInformation(counselSessionId, updateHealthInformationReq, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CounselCardControllerApi.updateCounselCardHealthInformation']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 상담 카드 자립생활 역량 수정
         * @param {string} counselSessionId 
         * @param {UpdateIndependentLifeInformationReq} updateIndependentLifeInformationReq 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateCounselCardIndependentLifeInformation(counselSessionId: string, updateIndependentLifeInformationReq: UpdateIndependentLifeInformationReq, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommonResCounselCardIdRes>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateCounselCardIndependentLifeInformation(counselSessionId, updateIndependentLifeInformationReq, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CounselCardControllerApi.updateCounselCardIndependentLifeInformation']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 상담 카드 생활 정보 수정
         * @param {string} counselSessionId 
         * @param {UpdateLivingInformationReq} updateLivingInformationReq 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateCounselCardLivingInformation(counselSessionId: string, updateLivingInformationReq: UpdateLivingInformationReq, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommonResCounselCardIdRes>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateCounselCardLivingInformation(counselSessionId, updateLivingInformationReq, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CounselCardControllerApi.updateCounselCardLivingInformation']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 상담 카드 상태 수정
         * @param {string} counselSessionId 
         * @param {UpdateCounselCardStatusReq} updateCounselCardStatusReq 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateCounselCardStatus(counselSessionId: string, updateCounselCardStatusReq: UpdateCounselCardStatusReq, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommonResCounselCardIdRes>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateCounselCardStatus(counselSessionId, updateCounselCardStatusReq, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CounselCardControllerApi.updateCounselCardStatus']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * CounselCardControllerApi - factory interface
 * @export
 */
export const CounselCardControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CounselCardControllerApiFp(configuration)
    return {
        /**
         * 
         * @summary 상담 카드 삭제
         * @param {string} counselSessionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteCounselCard(counselSessionId: string, options?: RawAxiosRequestConfig): AxiosPromise<CommonResCounselCardIdRes> {
            return localVarFp.deleteCounselCard(counselSessionId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 상담 카드 조회
         * @param {string} counselSessionId 
         * @param {*} [options] Override http request option.
         * @deprecated
         * @throws {RequiredError}
         */
        selectCounselCard(counselSessionId: string, options?: RawAxiosRequestConfig): AxiosPromise<CommonResCounselCardRes> {
            return localVarFp.selectCounselCard(counselSessionId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 상담 카드 기본 정보 조회
         * @param {string} counselSessionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        selectCounselCardBaseInformation(counselSessionId: string, options?: RawAxiosRequestConfig): AxiosPromise<CommonResCounselCardBaseInformationRes> {
            return localVarFp.selectCounselCardBaseInformation(counselSessionId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 상담 카드 건강 정보 조회
         * @param {string} counselSessionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        selectCounselCardHealthInformation(counselSessionId: string, options?: RawAxiosRequestConfig): AxiosPromise<CommonResCounselCardHealthInformationRes> {
            return localVarFp.selectCounselCardHealthInformation(counselSessionId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 상담 카드 자립생활 역량 조회
         * @param {string} counselSessionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        selectCounselCardIndependentLifeInformation(counselSessionId: string, options?: RawAxiosRequestConfig): AxiosPromise<CommonResCounselCardIndependentLifeInformationRes> {
            return localVarFp.selectCounselCardIndependentLifeInformation(counselSessionId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 상담 카드 생활 정보 조회
         * @param {string} counselSessionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        selectCounselCardLivingInformation(counselSessionId: string, options?: RawAxiosRequestConfig): AxiosPromise<CommonResCounselCardLivingInformationRes> {
            return localVarFp.selectCounselCardLivingInformation(counselSessionId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 이전 상담 카드 item 목록 조회
         * @param {string} counselSessionId 
         * @param {SelectPreviousItemListByInformationNameAndItemNameTypeEnum} type 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        selectPreviousItemListByInformationNameAndItemName(counselSessionId: string, type: SelectPreviousItemListByInformationNameAndItemNameTypeEnum, options?: RawAxiosRequestConfig): AxiosPromise<CommonResListTimeRecordedResObject> {
            return localVarFp.selectPreviousItemListByInformationNameAndItemName(counselSessionId, type, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 상담 카드 기본 정보 수정
         * @param {string} counselSessionId 
         * @param {UpdateBaseInformationReq} updateBaseInformationReq 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateCounselCardBaseInformation(counselSessionId: string, updateBaseInformationReq: UpdateBaseInformationReq, options?: RawAxiosRequestConfig): AxiosPromise<CommonResCounselCardIdRes> {
            return localVarFp.updateCounselCardBaseInformation(counselSessionId, updateBaseInformationReq, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 상담 카드 건강 정보 수정
         * @param {string} counselSessionId 
         * @param {UpdateHealthInformationReq} updateHealthInformationReq 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateCounselCardHealthInformation(counselSessionId: string, updateHealthInformationReq: UpdateHealthInformationReq, options?: RawAxiosRequestConfig): AxiosPromise<CommonResCounselCardIdRes> {
            return localVarFp.updateCounselCardHealthInformation(counselSessionId, updateHealthInformationReq, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 상담 카드 자립생활 역량 수정
         * @param {string} counselSessionId 
         * @param {UpdateIndependentLifeInformationReq} updateIndependentLifeInformationReq 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateCounselCardIndependentLifeInformation(counselSessionId: string, updateIndependentLifeInformationReq: UpdateIndependentLifeInformationReq, options?: RawAxiosRequestConfig): AxiosPromise<CommonResCounselCardIdRes> {
            return localVarFp.updateCounselCardIndependentLifeInformation(counselSessionId, updateIndependentLifeInformationReq, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 상담 카드 생활 정보 수정
         * @param {string} counselSessionId 
         * @param {UpdateLivingInformationReq} updateLivingInformationReq 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateCounselCardLivingInformation(counselSessionId: string, updateLivingInformationReq: UpdateLivingInformationReq, options?: RawAxiosRequestConfig): AxiosPromise<CommonResCounselCardIdRes> {
            return localVarFp.updateCounselCardLivingInformation(counselSessionId, updateLivingInformationReq, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 상담 카드 상태 수정
         * @param {string} counselSessionId 
         * @param {UpdateCounselCardStatusReq} updateCounselCardStatusReq 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateCounselCardStatus(counselSessionId: string, updateCounselCardStatusReq: UpdateCounselCardStatusReq, options?: RawAxiosRequestConfig): AxiosPromise<CommonResCounselCardIdRes> {
            return localVarFp.updateCounselCardStatus(counselSessionId, updateCounselCardStatusReq, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CounselCardControllerApi - object-oriented interface
 * @export
 * @class CounselCardControllerApi
 * @extends {BaseAPI}
 */
export class CounselCardControllerApi extends BaseAPI {
    /**
     * 
     * @summary 상담 카드 삭제
     * @param {string} counselSessionId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CounselCardControllerApi
     */
    public deleteCounselCard(counselSessionId: string, options?: RawAxiosRequestConfig) {
        return CounselCardControllerApiFp(this.configuration).deleteCounselCard(counselSessionId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 상담 카드 조회
     * @param {string} counselSessionId 
     * @param {*} [options] Override http request option.
     * @deprecated
     * @throws {RequiredError}
     * @memberof CounselCardControllerApi
     */
    public selectCounselCard(counselSessionId: string, options?: RawAxiosRequestConfig) {
        return CounselCardControllerApiFp(this.configuration).selectCounselCard(counselSessionId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 상담 카드 기본 정보 조회
     * @param {string} counselSessionId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CounselCardControllerApi
     */
    public selectCounselCardBaseInformation(counselSessionId: string, options?: RawAxiosRequestConfig) {
        return CounselCardControllerApiFp(this.configuration).selectCounselCardBaseInformation(counselSessionId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 상담 카드 건강 정보 조회
     * @param {string} counselSessionId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CounselCardControllerApi
     */
    public selectCounselCardHealthInformation(counselSessionId: string, options?: RawAxiosRequestConfig) {
        return CounselCardControllerApiFp(this.configuration).selectCounselCardHealthInformation(counselSessionId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 상담 카드 자립생활 역량 조회
     * @param {string} counselSessionId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CounselCardControllerApi
     */
    public selectCounselCardIndependentLifeInformation(counselSessionId: string, options?: RawAxiosRequestConfig) {
        return CounselCardControllerApiFp(this.configuration).selectCounselCardIndependentLifeInformation(counselSessionId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 상담 카드 생활 정보 조회
     * @param {string} counselSessionId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CounselCardControllerApi
     */
    public selectCounselCardLivingInformation(counselSessionId: string, options?: RawAxiosRequestConfig) {
        return CounselCardControllerApiFp(this.configuration).selectCounselCardLivingInformation(counselSessionId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 이전 상담 카드 item 목록 조회
     * @param {string} counselSessionId 
     * @param {SelectPreviousItemListByInformationNameAndItemNameTypeEnum} type 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CounselCardControllerApi
     */
    public selectPreviousItemListByInformationNameAndItemName(counselSessionId: string, type: SelectPreviousItemListByInformationNameAndItemNameTypeEnum, options?: RawAxiosRequestConfig) {
        return CounselCardControllerApiFp(this.configuration).selectPreviousItemListByInformationNameAndItemName(counselSessionId, type, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 상담 카드 기본 정보 수정
     * @param {string} counselSessionId 
     * @param {UpdateBaseInformationReq} updateBaseInformationReq 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CounselCardControllerApi
     */
    public updateCounselCardBaseInformation(counselSessionId: string, updateBaseInformationReq: UpdateBaseInformationReq, options?: RawAxiosRequestConfig) {
        return CounselCardControllerApiFp(this.configuration).updateCounselCardBaseInformation(counselSessionId, updateBaseInformationReq, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 상담 카드 건강 정보 수정
     * @param {string} counselSessionId 
     * @param {UpdateHealthInformationReq} updateHealthInformationReq 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CounselCardControllerApi
     */
    public updateCounselCardHealthInformation(counselSessionId: string, updateHealthInformationReq: UpdateHealthInformationReq, options?: RawAxiosRequestConfig) {
        return CounselCardControllerApiFp(this.configuration).updateCounselCardHealthInformation(counselSessionId, updateHealthInformationReq, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 상담 카드 자립생활 역량 수정
     * @param {string} counselSessionId 
     * @param {UpdateIndependentLifeInformationReq} updateIndependentLifeInformationReq 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CounselCardControllerApi
     */
    public updateCounselCardIndependentLifeInformation(counselSessionId: string, updateIndependentLifeInformationReq: UpdateIndependentLifeInformationReq, options?: RawAxiosRequestConfig) {
        return CounselCardControllerApiFp(this.configuration).updateCounselCardIndependentLifeInformation(counselSessionId, updateIndependentLifeInformationReq, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 상담 카드 생활 정보 수정
     * @param {string} counselSessionId 
     * @param {UpdateLivingInformationReq} updateLivingInformationReq 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CounselCardControllerApi
     */
    public updateCounselCardLivingInformation(counselSessionId: string, updateLivingInformationReq: UpdateLivingInformationReq, options?: RawAxiosRequestConfig) {
        return CounselCardControllerApiFp(this.configuration).updateCounselCardLivingInformation(counselSessionId, updateLivingInformationReq, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 상담 카드 상태 수정
     * @param {string} counselSessionId 
     * @param {UpdateCounselCardStatusReq} updateCounselCardStatusReq 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CounselCardControllerApi
     */
    public updateCounselCardStatus(counselSessionId: string, updateCounselCardStatusReq: UpdateCounselCardStatusReq, options?: RawAxiosRequestConfig) {
        return CounselCardControllerApiFp(this.configuration).updateCounselCardStatus(counselSessionId, updateCounselCardStatusReq, options).then((request) => request(this.axios, this.basePath));
    }
}

/**
 * @export
 */
export const SelectPreviousItemListByInformationNameAndItemNameTypeEnum = {
    Smoking: 'SMOKING',
    Drinking: 'DRINKING',
    Nutrition: 'NUTRITION',
    Exercise: 'EXERCISE',
    MedicationManagement: 'MEDICATION_MANAGEMENT',
    DiseaseInfo: 'DISEASE_INFO',
    Allergy: 'ALLERGY',
    MedicationSideEffect: 'MEDICATION_SIDE_EFFECT',
    CounselPurposeAndNote: 'COUNSEL_PURPOSE_AND_NOTE',
    Communication: 'COMMUNICATION',
    Evacuation: 'EVACUATION',
    Walking: 'WALKING'
} as const;
export type SelectPreviousItemListByInformationNameAndItemNameTypeEnum = typeof SelectPreviousItemListByInformationNameAndItemNameTypeEnum[keyof typeof SelectPreviousItemListByInformationNameAndItemNameTypeEnum];
