/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AddCounseleeReq
 */
export interface AddCounseleeReq {
    /**
     * 
     * @type {string}
     * @memberof AddCounseleeReq
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof AddCounseleeReq
     */
    'phoneNumber'?: string;
    /**
     * 
     * @type {string}
     * @memberof AddCounseleeReq
     */
    'dateOfBirth': string;
    /**
     * 
     * @type {string}
     * @memberof AddCounseleeReq
     */
    'genderType'?: AddCounseleeReqGenderTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof AddCounseleeReq
     */
    'address'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AddCounseleeReq
     */
    'isDisability'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AddCounseleeReq
     */
    'note'?: string;
    /**
     * 
     * @type {string}
     * @memberof AddCounseleeReq
     */
    'careManagerName'?: string;
    /**
     * 
     * @type {string}
     * @memberof AddCounseleeReq
     */
    'affiliatedWelfareInstitution'?: string;
}

export const AddCounseleeReqGenderTypeEnum = {
    Male: 'MALE',
    Female: 'FEMALE',
    Else: 'ELSE'
} as const;

export type AddCounseleeReqGenderTypeEnum = typeof AddCounseleeReqGenderTypeEnum[keyof typeof AddCounseleeReqGenderTypeEnum];


