/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SelectCounselSessionPageRes } from './select-counsel-session-page-res';

/**
 * 
 * @export
 * @interface CommonResSelectCounselSessionPageRes
 */
export interface CommonResSelectCounselSessionPageRes {
    /**
     * 
     * @type {string}
     * @memberof CommonResSelectCounselSessionPageRes
     */
    'message'?: string;
    /**
     * 
     * @type {SelectCounselSessionPageRes}
     * @memberof CommonResSelectCounselSessionPageRes
     */
    'data'?: SelectCounselSessionPageRes;
}

