/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AddMedicationCounselRes } from './add-medication-counsel-res';

/**
 * 
 * @export
 * @interface CommonResAddMedicationCounselRes
 */
export interface CommonResAddMedicationCounselRes {
    /**
     * 
     * @type {string}
     * @memberof CommonResAddMedicationCounselRes
     */
    'message'?: string;
    /**
     * 
     * @type {AddMedicationCounselRes}
     * @memberof CommonResAddMedicationCounselRes
     */
    'data'?: AddMedicationCounselRes;
}

