/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DeleteCounseleeBatchRes } from './delete-counselee-batch-res';

/**
 * 
 * @export
 * @interface CommonResListDeleteCounseleeBatchRes
 */
export interface CommonResListDeleteCounseleeBatchRes {
    /**
     * 
     * @type {string}
     * @memberof CommonResListDeleteCounseleeBatchRes
     */
    'message'?: string;
    /**
     * 
     * @type {Array<DeleteCounseleeBatchRes>}
     * @memberof CommonResListDeleteCounseleeBatchRes
     */
    'data'?: Array<DeleteCounseleeBatchRes>;
}

