/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CounselCardLivingInformationRes } from './counsel-card-living-information-res';

/**
 * 
 * @export
 * @interface CommonResCounselCardLivingInformationRes
 */
export interface CommonResCounselCardLivingInformationRes {
    /**
     * 
     * @type {string}
     * @memberof CommonResCounselCardLivingInformationRes
     */
    'message'?: string;
    /**
     * 
     * @type {CounselCardLivingInformationRes}
     * @memberof CommonResCounselCardLivingInformationRes
     */
    'data'?: CounselCardLivingInformationRes;
}

