/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { UpdateMedicationCounselRes } from './update-medication-counsel-res';

/**
 * 
 * @export
 * @interface CommonResUpdateMedicationCounselRes
 */
export interface CommonResUpdateMedicationCounselRes {
    /**
     * 
     * @type {string}
     * @memberof CommonResUpdateMedicationCounselRes
     */
    'message'?: string;
    /**
     * 
     * @type {UpdateMedicationCounselRes}
     * @memberof CommonResUpdateMedicationCounselRes
     */
    'data'?: UpdateMedicationCounselRes;
}

