/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AddAndUpdateWasteMedicationRecordRes } from './add-and-update-waste-medication-record-res';

/**
 * 
 * @export
 * @interface CommonResListAddAndUpdateWasteMedicationRecordRes
 */
export interface CommonResListAddAndUpdateWasteMedicationRecordRes {
    /**
     * 
     * @type {string}
     * @memberof CommonResListAddAndUpdateWasteMedicationRecordRes
     */
    'message'?: string;
    /**
     * 
     * @type {Array<AddAndUpdateWasteMedicationRecordRes>}
     * @memberof CommonResListAddAndUpdateWasteMedicationRecordRes
     */
    'data'?: Array<AddAndUpdateWasteMedicationRecordRes>;
}

