/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CommunicationDTO
 */
export interface CommunicationDTO {
    /**
     * 
     * @type {Array<string>}
     * @memberof CommunicationDTO
     */
    'sights'?: Array<CommunicationDTOSightsEnum>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CommunicationDTO
     */
    'hearings'?: Array<CommunicationDTOHearingsEnum>;
    /**
     * 
     * @type {string}
     * @memberof CommunicationDTO
     */
    'communications'?: CommunicationDTOCommunicationsEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof CommunicationDTO
     */
    'usingKoreans'?: Array<CommunicationDTOUsingKoreansEnum>;
}

export const CommunicationDTOSightsEnum = {
    WellSeen: 'WELL_SEEN',
    PoorlySeen: 'POORLY_SEEN',
    NotSeen: 'NOT_SEEN',
    UsingGlasses: 'USING_GLASSES'
} as const;

export type CommunicationDTOSightsEnum = typeof CommunicationDTOSightsEnum[keyof typeof CommunicationDTOSightsEnum];
export const CommunicationDTOHearingsEnum = {
    WellHeard: 'WELL_HEARD',
    PoorlyHeard: 'POORLY_HEARD',
    NotHeard: 'NOT_HEARD',
    UsingHearingAid: 'USING_HEARING_AID'
} as const;

export type CommunicationDTOHearingsEnum = typeof CommunicationDTOHearingsEnum[keyof typeof CommunicationDTOHearingsEnum];
export const CommunicationDTOCommunicationsEnum = {
    WellCommunicate: 'WELL_COMMUNICATE',
    SemiCommunicate: 'SEMI_COMMUNICATE',
    NotCommunicate: 'NOT_COMMUNICATE'
} as const;

export type CommunicationDTOCommunicationsEnum = typeof CommunicationDTOCommunicationsEnum[keyof typeof CommunicationDTOCommunicationsEnum];
export const CommunicationDTOUsingKoreansEnum = {
    Read: 'ABLE_TO_READ',
    Write: 'ABLE_TO_WRITE'
} as const;

export type CommunicationDTOUsingKoreansEnum = typeof CommunicationDTOUsingKoreansEnum[keyof typeof CommunicationDTOUsingKoreansEnum];


