/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CounselorInfoListRes
 */
export interface CounselorInfoListRes {
    /**
     * 
     * @type {string}
     * @memberof CounselorInfoListRes
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof CounselorInfoListRes
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof CounselorInfoListRes
     */
    'roleType'?: CounselorInfoListResRoleTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof CounselorInfoListRes
     */
    'username'?: string;
    /**
     * 
     * @type {string}
     * @memberof CounselorInfoListRes
     */
    'phoneNumber'?: string;
    /**
     * 
     * @type {string}
     * @memberof CounselorInfoListRes
     */
    'registrationDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof CounselorInfoListRes
     */
    'description'?: string;
}

export const CounselorInfoListResRoleTypeEnum = {
    Admin: 'ROLE_ADMIN',
    User: 'ROLE_USER',
    Assistant: 'ROLE_ASSISTANT',
    None: 'ROLE_NONE'
} as const;

export type CounselorInfoListResRoleTypeEnum = typeof CounselorInfoListResRoleTypeEnum[keyof typeof CounselorInfoListResRoleTypeEnum];


