/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AllergyDTO } from './allergy-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { BaseInfoDTO } from './base-info-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { CounselPurposeAndNoteDTO } from './counsel-purpose-and-note-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { DiseaseInfoDTO } from './disease-info-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { DrinkingDTO } from './drinking-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { ExerciseDTO } from './exercise-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { MedicationManagementDTO } from './medication-management-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { MedicationSideEffectDTO } from './medication-side-effect-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { NutritionDTO } from './nutrition-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { SmokingDTO } from './smoking-dto';

/**
 * 
 * @export
 * @interface CounselCardRes
 */
export interface CounselCardRes {
    /**
     * 
     * @type {BaseInfoDTO}
     * @memberof CounselCardRes
     */
    'baseInfo'?: BaseInfoDTO;
    /**
     * 
     * @type {string}
     * @memberof CounselCardRes
     */
    'cardRecordStatus'?: CounselCardResCardRecordStatusEnum;
    /**
     * 
     * @type {CounselPurposeAndNoteDTO}
     * @memberof CounselCardRes
     */
    'counselPurposeAndNote'?: CounselPurposeAndNoteDTO;
    /**
     * 
     * @type {AllergyDTO}
     * @memberof CounselCardRes
     */
    'allergy'?: AllergyDTO;
    /**
     * 
     * @type {DiseaseInfoDTO}
     * @memberof CounselCardRes
     */
    'diseaseInfo'?: DiseaseInfoDTO;
    /**
     * 
     * @type {MedicationSideEffectDTO}
     * @memberof CounselCardRes
     */
    'medicationSideEffect'?: MedicationSideEffectDTO;
    /**
     * 
     * @type {DrinkingDTO}
     * @memberof CounselCardRes
     */
    'drinking'?: DrinkingDTO;
    /**
     * 
     * @type {ExerciseDTO}
     * @memberof CounselCardRes
     */
    'exercise'?: ExerciseDTO;
    /**
     * 
     * @type {MedicationManagementDTO}
     * @memberof CounselCardRes
     */
    'medicationManagement'?: MedicationManagementDTO;
    /**
     * 
     * @type {NutritionDTO}
     * @memberof CounselCardRes
     */
    'nutrition'?: NutritionDTO;
    /**
     * 
     * @type {SmokingDTO}
     * @memberof CounselCardRes
     */
    'smoking'?: SmokingDTO;
}

export const CounselCardResCardRecordStatusEnum = {
    NotStarted: 'NOT_STARTED',
    InProgress: 'IN_PROGRESS',
    Completed: 'COMPLETED'
} as const;

export type CounselCardResCardRecordStatusEnum = typeof CounselCardResCardRecordStatusEnum[keyof typeof CounselCardResCardRecordStatusEnum];


