/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DrinkingDTO
 */
export interface DrinkingDTO {
    /**
     * 
     * @type {string}
     * @memberof DrinkingDTO
     */
    'drinkingAmount'?: DrinkingDTODrinkingAmountEnum;
}

export const DrinkingDTODrinkingAmountEnum = {
    None: 'NONE',
    OnceAWeek: 'ONCE_A_WEEK',
    TwiceAWeek: 'TWICE_A_WEEK',
    ThreeTimesAWeek: 'THREE_TIMES_A_WEEK',
    FourTimesAWeek: 'FOUR_TIMES_A_WEEK',
    FiveOrMoreTimesAWeek: 'FIVE_OR_MORE_TIMES_A_WEEK'
} as const;

export type DrinkingDTODrinkingAmountEnum = typeof DrinkingDTODrinkingAmountEnum[keyof typeof DrinkingDTODrinkingAmountEnum];


