/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ExerciseDTO } from './exercise-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { TimeRecordedResExerciseDTO } from './time-recorded-res-exercise-dto';

/**
 * 
 * @export
 * @interface MainCounselRecordExerciseDTO
 */
export interface MainCounselRecordExerciseDTO {
    /**
     * 
     * @type {ExerciseDTO}
     * @memberof MainCounselRecordExerciseDTO
     */
    'currentState'?: ExerciseDTO;
    /**
     * 
     * @type {Array<TimeRecordedResExerciseDTO>}
     * @memberof MainCounselRecordExerciseDTO
     */
    'history'?: Array<TimeRecordedResExerciseDTO>;
}

