/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MedicationManagementDTO } from './medication-management-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { TimeRecordedResMedicationManagementDTO } from './time-recorded-res-medication-management-dto';

/**
 * 
 * @export
 * @interface MainCounselRecordMedicationManagementDTO
 */
export interface MainCounselRecordMedicationManagementDTO {
    /**
     * 
     * @type {MedicationManagementDTO}
     * @memberof MainCounselRecordMedicationManagementDTO
     */
    'currentState'?: MedicationManagementDTO;
    /**
     * 
     * @type {Array<TimeRecordedResMedicationManagementDTO>}
     * @memberof MainCounselRecordMedicationManagementDTO
     */
    'history'?: Array<TimeRecordedResMedicationManagementDTO>;
}

