/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EvacuationDTO } from './evacuation-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { TimeRecordedResEvacuationDTO } from './time-recorded-res-evacuation-dto';

/**
 * 
 * @export
 * @interface MainCounselRecordEvacuationDTO
 */
export interface MainCounselRecordEvacuationDTO {
    /**
     * 
     * @type {EvacuationDTO}
     * @memberof MainCounselRecordEvacuationDTO
     */
    'currentState'?: EvacuationDTO;
    /**
     * 
     * @type {Array<TimeRecordedResEvacuationDTO>}
     * @memberof MainCounselRecordEvacuationDTO
     */
    'history'?: Array<TimeRecordedResEvacuationDTO>;
}

