/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MainCounselRecordDrinkingAmount } from './main-counsel-record-drinking-amount';
// May contain unused imports in some cases
// @ts-ignore
import type { MainCounselRecordExerciseDTO } from './main-counsel-record-exercise-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { MainCounselRecordMedicationManagementDTO } from './main-counsel-record-medication-management-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { MainCounselRecordNutritionDTO } from './main-counsel-record-nutrition-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { MainCounselRecordSmokingDTO } from './main-counsel-record-smoking-dto';

/**
 * 
 * @export
 * @interface MainCounselLivingInformationRes
 */
export interface MainCounselLivingInformationRes {
    /**
     * 
     * @type {MainCounselRecordSmokingDTO}
     * @memberof MainCounselLivingInformationRes
     */
    'smoking'?: MainCounselRecordSmokingDTO;
    /**
     * 
     * @type {MainCounselRecordDrinkingAmount}
     * @memberof MainCounselLivingInformationRes
     */
    'drinkingAmount'?: MainCounselRecordDrinkingAmount;
    /**
     * 
     * @type {MainCounselRecordExerciseDTO}
     * @memberof MainCounselLivingInformationRes
     */
    'exercise'?: MainCounselRecordExerciseDTO;
    /**
     * 
     * @type {MainCounselRecordMedicationManagementDTO}
     * @memberof MainCounselLivingInformationRes
     */
    'medicationManagement'?: MainCounselRecordMedicationManagementDTO;
    /**
     * 
     * @type {MainCounselRecordNutritionDTO}
     * @memberof MainCounselLivingInformationRes
     */
    'nutrition'?: MainCounselRecordNutritionDTO;
}

