/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MainCounselRecordListCounselPurposeType } from './main-counsel-record-list-counsel-purpose-type';
// May contain unused imports in some cases
// @ts-ignore
import type { MainCounselRecordString } from './main-counsel-record-string';

/**
 * 
 * @export
 * @interface MainCounselBaseInformationRes
 */
export interface MainCounselBaseInformationRes {
    /**
     * 
     * @type {MainCounselRecordListCounselPurposeType}
     * @memberof MainCounselBaseInformationRes
     */
    'counselPurpose'?: MainCounselRecordListCounselPurposeType;
    /**
     * 
     * @type {MainCounselRecordString}
     * @memberof MainCounselBaseInformationRes
     */
    'significantNote'?: MainCounselRecordString;
    /**
     * 
     * @type {MainCounselRecordString}
     * @memberof MainCounselBaseInformationRes
     */
    'medicationNote'?: MainCounselRecordString;
}

