/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TimeRecordedResListCounselPurposeType } from './time-recorded-res-list-counsel-purpose-type';

/**
 * 
 * @export
 * @interface MainCounselRecordListCounselPurposeType
 */
export interface MainCounselRecordListCounselPurposeType {
    /**
     * 
     * @type {Array<string>}
     * @memberof MainCounselRecordListCounselPurposeType
     */
    'currentState'?: Array<MainCounselRecordListCounselPurposeTypeCurrentStateEnum>;
    /**
     * 
     * @type {Array<TimeRecordedResListCounselPurposeType>}
     * @memberof MainCounselRecordListCounselPurposeType
     */
    'history'?: Array<TimeRecordedResListCounselPurposeType>;
}

export const MainCounselRecordListCounselPurposeTypeCurrentStateEnum = {
    MedicationSideEffect: 'MEDICATION_SIDE_EFFECT',
    LifestyleManagement: 'LIFESTYLE_MANAGEMENT',
    SymptomDiseaseUnderstanding: 'SYMPTOM_DISEASE_UNDERSTANDING',
    MedicationReview: 'MEDICATION_REVIEW',
    Other: 'OTHER'
} as const;

export type MainCounselRecordListCounselPurposeTypeCurrentStateEnum = typeof MainCounselRecordListCounselPurposeTypeCurrentStateEnum[keyof typeof MainCounselRecordListCounselPurposeTypeCurrentStateEnum];


