/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MainCounselRecordAllergyDTO } from './main-counsel-record-allergy-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { MainCounselRecordListDiseaseType } from './main-counsel-record-list-disease-type';
// May contain unused imports in some cases
// @ts-ignore
import type { MainCounselRecordMedicationSideEffectDTO } from './main-counsel-record-medication-side-effect-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { MainCounselRecordString } from './main-counsel-record-string';

/**
 * 
 * @export
 * @interface MainCounselHealthInformationRes
 */
export interface MainCounselHealthInformationRes {
    /**
     * 
     * @type {MainCounselRecordListDiseaseType}
     * @memberof MainCounselHealthInformationRes
     */
    'diseases'?: MainCounselRecordListDiseaseType;
    /**
     * 
     * @type {MainCounselRecordString}
     * @memberof MainCounselHealthInformationRes
     */
    'historyNote'?: MainCounselRecordString;
    /**
     * 
     * @type {MainCounselRecordString}
     * @memberof MainCounselHealthInformationRes
     */
    'mainInconvenienceNote'?: MainCounselRecordString;
    /**
     * 
     * @type {MainCounselRecordMedicationSideEffectDTO}
     * @memberof MainCounselHealthInformationRes
     */
    'medicationSideEffect'?: MainCounselRecordMedicationSideEffectDTO;
    /**
     * 
     * @type {MainCounselRecordAllergyDTO}
     * @memberof MainCounselHealthInformationRes
     */
    'allergy'?: MainCounselRecordAllergyDTO;
}

