/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TimeRecordedResListDiseaseType } from './time-recorded-res-list-disease-type';

/**
 * 
 * @export
 * @interface MainCounselRecordListDiseaseType
 */
export interface MainCounselRecordListDiseaseType {
    /**
     * 
     * @type {Array<string>}
     * @memberof MainCounselRecordListDiseaseType
     */
    'currentState'?: Array<MainCounselRecordListDiseaseTypeCurrentStateEnum>;
    /**
     * 
     * @type {Array<TimeRecordedResListDiseaseType>}
     * @memberof MainCounselRecordListDiseaseType
     */
    'history'?: Array<TimeRecordedResListDiseaseType>;
}

export const MainCounselRecordListDiseaseTypeCurrentStateEnum = {
    Hypertension: 'HYPERTENSION',
    Hyperlipidemia: 'HYPERLIPIDEMIA',
    CerebrovascularDisease: 'CEREBROVASCULAR_DISEASE',
    HeartDisease: 'HEART_DISEASE',
    Diabetes: 'DIABETES',
    ThyroidDisease: 'THYROID_DISEASE',
    GastrointestinalDisease: 'GASTROINTESTINAL_DISEASE',
    ParkinsonsDisease: 'PARKINSONS_DISEASE',
    Dementia: 'DEMENTIA',
    SleepDisorder: 'SLEEP_DISORDER',
    DepressionAnxiety: 'DEPRESSION_ANXIETY',
    KidneyDisease: 'KIDNEY_DISEASE',
    LiverDisease: 'LIVER_DISEASE',
    UrogenitalDisease: 'UROGENITAL_DISEASE',
    Cancer: 'CANCER',
    Stroke: 'STROKE',
    SpineJointNeuropathy: 'SPINE_JOINT_NEUROPATHY',
    RespiratoryDisease: 'RESPIRATORY_DISEASE',
    EyeDisease: 'EYE_DISEASE',
    EntDisease: 'ENT_DISEASE'
} as const;

export type MainCounselRecordListDiseaseTypeCurrentStateEnum = typeof MainCounselRecordListDiseaseTypeCurrentStateEnum[keyof typeof MainCounselRecordListDiseaseTypeCurrentStateEnum];


