/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ModifyCounselReservationReq
 */
export interface ModifyCounselReservationReq {
    /**
     * 
     * @type {string}
     * @memberof ModifyCounselReservationReq
     */
    'counselSessionId'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModifyCounselReservationReq
     */
    'counseleeId'?: string;
    /**
     * 상담 일정 날짜 및 시간
     * @type {string}
     * @memberof ModifyCounselReservationReq
     */
    'scheduledStartDateTime'?: string;
}

