/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface NutritionDTO
 */
export interface NutritionDTO {
    /**
     * 
     * @type {string}
     * @memberof NutritionDTO
     */
    'mealPattern'?: NutritionDTOMealPatternEnum;
    /**
     * 
     * @type {string}
     * @memberof NutritionDTO
     */
    'nutritionNote'?: string;
}

export const NutritionDTOMealPatternEnum = {
    OneRegularMeal: 'ONE_REGULAR_MEAL',
    TwoRegularMeals: 'TWO_REGULAR_MEALS',
    ThreeRegularMeals: 'THREE_REGULAR_MEALS',
    IrregularMeals: 'IRREGULAR_MEALS'
} as const;

export type NutritionDTOMealPatternEnum = typeof NutritionDTOMealPatternEnum[keyof typeof NutritionDTOMealPatternEnum];


