/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PageRes
 */
export interface PageRes {
    /**
     * 
     * @type {number}
     * @memberof PageRes
     */
    'totalPages'?: number;
    /**
     * 
     * @type {number}
     * @memberof PageRes
     */
    'totalElements'?: number;
    /**
     * 
     * @type {number}
     * @memberof PageRes
     */
    'currentPage'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PageRes
     */
    'hasNext'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PageRes
     */
    'hasPrevious'?: boolean;
}

