/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PageRes } from './page-res';
// May contain unused imports in some cases
// @ts-ignore
import type { SelectCounseleeRes } from './select-counselee-res';

/**
 * 
 * @export
 * @interface SelectCounseleePageRes
 */
export interface SelectCounseleePageRes {
    /**
     * 
     * @type {PageRes}
     * @memberof SelectCounseleePageRes
     */
    'pageInfo'?: PageRes;
    /**
     * 
     * @type {Array<SelectCounseleeRes>}
     * @memberof SelectCounseleePageRes
     */
    'content'?: Array<SelectCounseleeRes>;
}

