/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 내담자 자동완성 응답
 * @export
 * @interface SelectCounseleeAutocompleteRes
 */
export interface SelectCounseleeAutocompleteRes {
    /**
     * 내담자 ID
     * @type {string}
     * @memberof SelectCounseleeAutocompleteRes
     */
    'counseleeId'?: string;
    /**
     * 내담자 이름
     * @type {string}
     * @memberof SelectCounseleeAutocompleteRes
     */
    'name'?: string;
    /**
     * 생년월일
     * @type {string}
     * @memberof SelectCounseleeAutocompleteRes
     */
    'birthDate'?: string;
}

