/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SelectCounseleeConsentByCounseleeIdRes
 */
export interface SelectCounseleeConsentByCounseleeIdRes {
    /**
     * 
     * @type {string}
     * @memberof SelectCounseleeConsentByCounseleeIdRes
     */
    'counseleeConsentId'?: string;
    /**
     * 
     * @type {string}
     * @memberof SelectCounseleeConsentByCounseleeIdRes
     */
    'counseleeId'?: string;
    /**
     * 
     * @type {string}
     * @memberof SelectCounseleeConsentByCounseleeIdRes
     */
    'counseleeName'?: string;
    /**
     * 
     * @type {string}
     * @memberof SelectCounseleeConsentByCounseleeIdRes
     */
    'counselSessionId'?: string;
    /**
     * 
     * @type {string}
     * @memberof SelectCounseleeConsentByCounseleeIdRes
     */
    'consentDateTime'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof SelectCounseleeConsentByCounseleeIdRes
     */
    'isConsent'?: boolean;
}

