/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SelectPreviousCounselSessionListRes
 */
export interface SelectPreviousCounselSessionListRes {
    /**
     * 
     * @type {string}
     * @memberof SelectPreviousCounselSessionListRes
     */
    'counselSessionId'?: string;
    /**
     * 
     * @type {number}
     * @memberof SelectPreviousCounselSessionListRes
     */
    'CounselSessionOrder'?: number;
    /**
     * 
     * @type {string}
     * @memberof SelectPreviousCounselSessionListRes
     */
    'counselSessionDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof SelectPreviousCounselSessionListRes
     */
    'counselorName'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof SelectPreviousCounselSessionListRes
     */
    'isShardCaringMessage'?: boolean;
}

