/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SelectCounseleeBaseInformationByCounseleeIdRes
 */
export interface SelectCounseleeBaseInformationByCounseleeIdRes {
    /**
     * 
     * @type {string}
     * @memberof SelectCounseleeBaseInformationByCounseleeIdRes
     */
    'counseleeId'?: string;
    /**
     * 
     * @type {string}
     * @memberof SelectCounseleeBaseInformationByCounseleeIdRes
     */
    'name'?: string;
    /**
     * 
     * @type {number}
     * @memberof SelectCounseleeBaseInformationByCounseleeIdRes
     */
    'age'?: number;
    /**
     * 
     * @type {string}
     * @memberof SelectCounseleeBaseInformationByCounseleeIdRes
     */
    'dateOfBirth'?: string;
    /**
     * 
     * @type {string}
     * @memberof SelectCounseleeBaseInformationByCounseleeIdRes
     */
    'gender'?: SelectCounseleeBaseInformationByCounseleeIdResGenderEnum;
    /**
     * 
     * @type {string}
     * @memberof SelectCounseleeBaseInformationByCounseleeIdRes
     */
    'address'?: string;
    /**
     * 
     * @type {string}
     * @memberof SelectCounseleeBaseInformationByCounseleeIdRes
     */
    'healthInsuranceType'?: SelectCounseleeBaseInformationByCounseleeIdResHealthInsuranceTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof SelectCounseleeBaseInformationByCounseleeIdRes
     */
    'counselCount'?: number;
    /**
     * 
     * @type {string}
     * @memberof SelectCounseleeBaseInformationByCounseleeIdRes
     */
    'lastCounselDate'?: string;
    /**
     * 
     * @type {Set<string>}
     * @memberof SelectCounseleeBaseInformationByCounseleeIdRes
     */
    'diseases'?: Set<SelectCounseleeBaseInformationByCounseleeIdResDiseasesEnum>;
    /**
     * 
     * @type {string}
     * @memberof SelectCounseleeBaseInformationByCounseleeIdRes
     */
    'cardRecordStatus'?: SelectCounseleeBaseInformationByCounseleeIdResCardRecordStatusEnum;
    /**
     * 
     * @type {boolean}
     * @memberof SelectCounseleeBaseInformationByCounseleeIdRes
     */
    'isDisability'?: boolean;
}

export const SelectCounseleeBaseInformationByCounseleeIdResGenderEnum = {
    Male: 'MALE',
    Female: 'FEMALE',
    Else: 'ELSE'
} as const;

export type SelectCounseleeBaseInformationByCounseleeIdResGenderEnum = typeof SelectCounseleeBaseInformationByCounseleeIdResGenderEnum[keyof typeof SelectCounseleeBaseInformationByCounseleeIdResGenderEnum];
export const SelectCounseleeBaseInformationByCounseleeIdResHealthInsuranceTypeEnum = {
    HealthInsurance: 'HEALTH_INSURANCE',
    MedicalAid: 'MEDICAL_AID',
    VeteransBenefits: 'VETERANS_BENEFITS',
    NonCovered: 'NON_COVERED'
} as const;

export type SelectCounseleeBaseInformationByCounseleeIdResHealthInsuranceTypeEnum = typeof SelectCounseleeBaseInformationByCounseleeIdResHealthInsuranceTypeEnum[keyof typeof SelectCounseleeBaseInformationByCounseleeIdResHealthInsuranceTypeEnum];
export const SelectCounseleeBaseInformationByCounseleeIdResDiseasesEnum = {
    Hypertension: 'HYPERTENSION',
    Hyperlipidemia: 'HYPERLIPIDEMIA',
    CerebrovascularDisease: 'CEREBROVASCULAR_DISEASE',
    HeartDisease: 'HEART_DISEASE',
    Diabetes: 'DIABETES',
    ThyroidDisease: 'THYROID_DISEASE',
    GastrointestinalDisease: 'GASTROINTESTINAL_DISEASE',
    ParkinsonsDisease: 'PARKINSONS_DISEASE',
    Dementia: 'DEMENTIA',
    SleepDisorder: 'SLEEP_DISORDER',
    DepressionAnxiety: 'DEPRESSION_ANXIETY',
    KidneyDisease: 'KIDNEY_DISEASE',
    LiverDisease: 'LIVER_DISEASE',
    UrogenitalDisease: 'UROGENITAL_DISEASE',
    Cancer: 'CANCER',
    Stroke: 'STROKE',
    SpineJointNeuropathy: 'SPINE_JOINT_NEUROPATHY',
    RespiratoryDisease: 'RESPIRATORY_DISEASE',
    EyeDisease: 'EYE_DISEASE',
    EntDisease: 'ENT_DISEASE'
} as const;

export type SelectCounseleeBaseInformationByCounseleeIdResDiseasesEnum = typeof SelectCounseleeBaseInformationByCounseleeIdResDiseasesEnum[keyof typeof SelectCounseleeBaseInformationByCounseleeIdResDiseasesEnum];
export const SelectCounseleeBaseInformationByCounseleeIdResCardRecordStatusEnum = {
    NotStarted: 'NOT_STARTED',
    InProgress: 'IN_PROGRESS',
    Completed: 'COMPLETED'
} as const;

export type SelectCounseleeBaseInformationByCounseleeIdResCardRecordStatusEnum = typeof SelectCounseleeBaseInformationByCounseleeIdResCardRecordStatusEnum[keyof typeof SelectCounseleeBaseInformationByCounseleeIdResCardRecordStatusEnum];


