/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SelectAICounselSummaryStatusRes
 */
export interface SelectAICounselSummaryStatusRes {
    /**
     * 
     * @type {string}
     * @memberof SelectAICounselSummaryStatusRes
     */
    'aiCounselSummaryStatus'?: SelectAICounselSummaryStatusResAiCounselSummaryStatusEnum;
}

export const SelectAICounselSummaryStatusResAiCounselSummaryStatusEnum = {
    SttProgress: 'STT_PROGRESS',
    SttFailed: 'STT_FAILED',
    SttComplete: 'STT_COMPLETE',
    GptProgress: 'GPT_PROGRESS',
    GptComplete: 'GPT_COMPLETE',
    GptFailed: 'GPT_FAILED'
} as const;

export type SelectAICounselSummaryStatusResAiCounselSummaryStatusEnum = typeof SelectAICounselSummaryStatusResAiCounselSummaryStatusEnum[keyof typeof SelectAICounselSummaryStatusResAiCounselSummaryStatusEnum];


