/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SelectPreviousCounselSessionDetailRes
 */
export interface SelectPreviousCounselSessionDetailRes {
    /**
     * 
     * @type {string}
     * @memberof SelectPreviousCounselSessionDetailRes
     */
    'counselSessionId'?: string;
    /**
     * 
     * @type {string}
     * @memberof SelectPreviousCounselSessionDetailRes
     */
    'counselSessionDate'?: string;
    /**
     * 
     * @type {number}
     * @memberof SelectPreviousCounselSessionDetailRes
     */
    'sessionNumber'?: number;
    /**
     * 
     * @type {string}
     * @memberof SelectPreviousCounselSessionDetailRes
     */
    'counselorName'?: string;
    /**
     * 
     * @type {string}
     * @memberof SelectPreviousCounselSessionDetailRes
     */
    'medicationCounselRecord'?: string;
    /**
     * 
     * @type {string}
     * @memberof SelectPreviousCounselSessionDetailRes
     */
    'aiSummary'?: string;
}

