/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SelectSpeechToTextRes
 */
export interface SelectSpeechToTextRes {
    /**
     * 
     * @type {string}
     * @memberof SelectSpeechToTextRes
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof SelectSpeechToTextRes
     */
    'text'?: string;
    /**
     * 
     * @type {string}
     * @memberof SelectSpeechToTextRes
     */
    'startTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof SelectSpeechToTextRes
     */
    'endTime'?: string;
}

