/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SmokingDTO
 */
export interface SmokingDTO {
    /**
     * 
     * @type {string}
     * @memberof SmokingDTO
     */
    'smokingPeriodNote'?: string;
    /**
     * 
     * @type {string}
     * @memberof SmokingDTO
     */
    'smokingAmount'?: SmokingDTOSmokingAmountEnum;
}

export const SmokingDTOSmokingAmountEnum = {
    None: 'NONE',
    OnePack: 'ONE_PACK',
    TwoPacks: 'TWO_PACKS',
    ThreeOrMorePacks: 'THREE_OR_MORE_PACKS'
} as const;

export type SmokingDTOSmokingAmountEnum = typeof SmokingDTOSmokingAmountEnum[keyof typeof SmokingDTOSmokingAmountEnum];


