/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CommunicationDTO } from './communication-dto';

/**
 * 
 * @export
 * @interface TimeRecordedResCommunicationDTO
 */
export interface TimeRecordedResCommunicationDTO {
    /**
     * 
     * @type {string}
     * @memberof TimeRecordedResCommunicationDTO
     */
    'counselDate'?: string;
    /**
     * 
     * @type {CommunicationDTO}
     * @memberof TimeRecordedResCommunicationDTO
     */
    'data'?: CommunicationDTO;
}

