/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { WalkingDTO } from './walking-dto';

/**
 * 
 * @export
 * @interface TimeRecordedResWalkingDTO
 */
export interface TimeRecordedResWalkingDTO {
    /**
     * 
     * @type {string}
     * @memberof TimeRecordedResWalkingDTO
     */
    'counselDate'?: string;
    /**
     * 
     * @type {WalkingDTO}
     * @memberof TimeRecordedResWalkingDTO
     */
    'data'?: WalkingDTO;
}

