/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TimeRecordedResListCounselPurposeType
 */
export interface TimeRecordedResListCounselPurposeType {
    /**
     * 
     * @type {string}
     * @memberof TimeRecordedResListCounselPurposeType
     */
    'counselDate'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof TimeRecordedResListCounselPurposeType
     */
    'data'?: Array<TimeRecordedResListCounselPurposeTypeDataEnum>;
}

export const TimeRecordedResListCounselPurposeTypeDataEnum = {
    MedicationSideEffect: 'MEDICATION_SIDE_EFFECT',
    LifestyleManagement: 'LIFESTYLE_MANAGEMENT',
    SymptomDiseaseUnderstanding: 'SYMPTOM_DISEASE_UNDERSTANDING',
    MedicationReview: 'MEDICATION_REVIEW',
    Other: 'OTHER'
} as const;

export type TimeRecordedResListCounselPurposeTypeDataEnum = typeof TimeRecordedResListCounselPurposeTypeDataEnum[keyof typeof TimeRecordedResListCounselPurposeTypeDataEnum];


