/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TimeRecordedResListDiseaseType
 */
export interface TimeRecordedResListDiseaseType {
    /**
     * 
     * @type {string}
     * @memberof TimeRecordedResListDiseaseType
     */
    'counselDate'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof TimeRecordedResListDiseaseType
     */
    'data'?: Array<TimeRecordedResListDiseaseTypeDataEnum>;
}

export const TimeRecordedResListDiseaseTypeDataEnum = {
    Hypertension: 'HYPERTENSION',
    Hyperlipidemia: 'HYPERLIPIDEMIA',
    CerebrovascularDisease: 'CEREBROVASCULAR_DISEASE',
    HeartDisease: 'HEART_DISEASE',
    Diabetes: 'DIABETES',
    ThyroidDisease: 'THYROID_DISEASE',
    GastrointestinalDisease: 'GASTROINTESTINAL_DISEASE',
    ParkinsonsDisease: 'PARKINSONS_DISEASE',
    Dementia: 'DEMENTIA',
    SleepDisorder: 'SLEEP_DISORDER',
    DepressionAnxiety: 'DEPRESSION_ANXIETY',
    KidneyDisease: 'KIDNEY_DISEASE',
    LiverDisease: 'LIVER_DISEASE',
    UrogenitalDisease: 'UROGENITAL_DISEASE',
    Cancer: 'CANCER',
    Stroke: 'STROKE',
    SpineJointNeuropathy: 'SPINE_JOINT_NEUROPATHY',
    RespiratoryDisease: 'RESPIRATORY_DISEASE',
    EyeDisease: 'EYE_DISEASE',
    EntDisease: 'ENT_DISEASE'
} as const;

export type TimeRecordedResListDiseaseTypeDataEnum = typeof TimeRecordedResListDiseaseTypeDataEnum[keyof typeof TimeRecordedResListDiseaseTypeDataEnum];


