/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateCounselCardStatusReq
 */
export interface UpdateCounselCardStatusReq {
    /**
     * 
     * @type {string}
     * @memberof UpdateCounselCardStatusReq
     */
    'status'?: UpdateCounselCardStatusReqStatusEnum;
}

export const UpdateCounselCardStatusReqStatusEnum = {
    NotStarted: 'NOT_STARTED',
    InProgress: 'IN_PROGRESS',
    Completed: 'COMPLETED'
} as const;

export type UpdateCounselCardStatusReqStatusEnum = typeof UpdateCounselCardStatusReqStatusEnum[keyof typeof UpdateCounselCardStatusReqStatusEnum];


