/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateRoleReq
 */
export interface UpdateRoleReq {
    /**
     * 
     * @type {string}
     * @memberof UpdateRoleReq
     */
    'roleType': UpdateRoleReqRoleTypeEnum;
}

export const UpdateRoleReqRoleTypeEnum = {
    Admin: 'ROLE_ADMIN',
    User: 'ROLE_USER',
    Assistant: 'ROLE_ASSISTANT',
    None: 'ROLE_NONE'
} as const;

export type UpdateRoleReqRoleTypeEnum = typeof UpdateRoleReqRoleTypeEnum[keyof typeof UpdateRoleReqRoleTypeEnum];


