/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateCounselorRes
 */
export interface UpdateCounselorRes {
    /**
     * 
     * @type {string}
     * @memberof UpdateCounselorRes
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCounselorRes
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCounselorRes
     */
    'roleType'?: UpdateCounselorResRoleTypeEnum;
}

export const UpdateCounselorResRoleTypeEnum = {
    Admin: 'ROLE_ADMIN',
    User: 'ROLE_USER',
    Assistant: 'ROLE_ASSISTANT',
    None: 'ROLE_NONE'
} as const;

export type UpdateCounselorResRoleTypeEnum = typeof UpdateCounselorResRoleTypeEnum[keyof typeof UpdateCounselorResRoleTypeEnum];


