/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface WasteMedicationDisposal
 */
export interface WasteMedicationDisposal {
    /**
     * 
     * @type {string}
     * @memberof WasteMedicationDisposal
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof WasteMedicationDisposal
     */
    'createdDatetime'?: string;
    /**
     * 
     * @type {string}
     * @memberof WasteMedicationDisposal
     */
    'updatedDatetime'?: string;
    /**
     * 
     * @type {string}
     * @memberof WasteMedicationDisposal
     */
    'createdBy'?: string;
    /**
     * 
     * @type {string}
     * @memberof WasteMedicationDisposal
     */
    'updatedBy'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof WasteMedicationDisposal
     */
    'unusedReasons'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof WasteMedicationDisposal
     */
    'unusedReasonDetail'?: string;
    /**
     * 
     * @type {string}
     * @memberof WasteMedicationDisposal
     */
    'drugRemainActionType'?: WasteMedicationDisposalDrugRemainActionTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof WasteMedicationDisposal
     */
    'drugRemainActionDetail'?: string;
    /**
     * 
     * @type {string}
     * @memberof WasteMedicationDisposal
     */
    'recoveryAgreementType'?: WasteMedicationDisposalRecoveryAgreementTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof WasteMedicationDisposal
     */
    'wasteMedicationGram'?: number;
}

export const WasteMedicationDisposalDrugRemainActionTypeEnum = {
    DoctorOrPharmacist: 'DOCTOR_OR_PHARMACIST',
    SelfDecision: 'SELF_DECISION',
    None: 'NONE'
} as const;

export type WasteMedicationDisposalDrugRemainActionTypeEnum = typeof WasteMedicationDisposalDrugRemainActionTypeEnum[keyof typeof WasteMedicationDisposalDrugRemainActionTypeEnum];
export const WasteMedicationDisposalRecoveryAgreementTypeEnum = {
    Agree: 'AGREE',
    Disagree: 'DISAGREE'
} as const;

export type WasteMedicationDisposalRecoveryAgreementTypeEnum = typeof WasteMedicationDisposalRecoveryAgreementTypeEnum[keyof typeof WasteMedicationDisposalRecoveryAgreementTypeEnum];


